apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-deployment
   labels:
     app: app-v1
spec:
  replicas: 2
  selector:
    matchLabels:
       app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
    spec:
      containers:
      - name: sample-container
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  labels:
    app: app-v1
spec:
  selector:
    app: app-v1
  ports:
  - port: 80
    protocol: TCP